# Project information
site_name: Hello Netdev
site_url: https://hello-netdev.littlesirius.top/
site_author: Xiao-Jiang-233
site_description: hello-网设
site_dir: site
# Repository
repo_name: Xiao-Jiang-233/hello-netdev
repo_url: https://github.com/Xiao-Jiang-233/hello-netdev
edit_uri: tree/main/docs
# version:

# Copyright
copyright: Copyright &copy; 2024 小将<br>The website content is licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a>

# Configuration
theme:
  name: material
  custom_dir: overrides
  language: zh
  features:
    - announce.dismiss
    - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    # - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: white
      accent: teal
      toggle:
        icon: material/theme-light-dark
        name: 深色模式
    - scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/theme-light-dark
        name: 浅色模式
  font:
    text: Noto Sans SC
    code: Fira Code
  # favicon: assets/images/favicon.png
  # logo: assets/images/logo.svg
  # icon:
  #   logo: logo
  #   repo: fontawesome/brands/github
  #   edit: fontawesome/regular/pen-to-square

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Xiao-Jiang-233
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/51896751
      name: Bilibili
    - icon: material/email
      link: mailto:hello-netdev@littlesirius.top
      name: Email
  generator: ture
  status:
    new: 最近添加

# Plugins
plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: none
      width: 100%
      height: auto
      zoomable: true
      draggable: false
      auto_caption: false
      caption_position: bottom
  - print-site:
      add_to_navigation: true
      print_page_title: "获得PDF"
      add_print_site_banner: false
      # Table of contents
      add_table_of_contents: true
      toc_title: "目录"
      toc_depth: 6
      # Content-related
      add_full_urls: false
      enumerate_headings: true
      enumerate_figures: true
      add_cover_page: true
      cover_page_template: ""
      path_to_pdf: ""
      include_css: false
      enabled: true
      exclude:

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  #     emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  # - pymdownx.magiclink:
  #     repo_url_shorthand: true
  #     user: squidfunk
  #     repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - stylesheets/extra.css

# Page tree
nav:
  - 序:
      - chapter_hello_netdev/index.md
  - 第 1 章 &nbsp; 设备的基本配置:
      - 批量配置: chapter_basic_configuration/port_group.md
  - 第 2 章 &nbsp; VLAN:
      - chapter_vlan/index.md
      - 2.1 &nbsp; 创建 VLAN: chapter_vlan/create_vlan.md
      - 2.2 &nbsp; VLAN端口配置: chapter_vlan/port_configuration.md
      - 2.3 &nbsp; VLAN间通信: chapter_vlan/inter-vlan_communication.md
      - 2.4 &nbsp; GVRP: chapter_vlan/gvrp.md
      - 2.5 &nbsp; 链路聚合: chapter_vlan/link_aggregation.md
  - 第 3 章 &nbsp; STP:
      - chapter_stp/index.md
      - 3.1 &nbsp; STP基础操作: chapter_stp/basic_operations.md
  - 第 4 章 &nbsp; 路由技术:
      - chapter_route/index.md
      - 4.1 &nbsp; 静态路由: chapter_route/static_routing.md
      - 4.2 &nbsp; 动态路由:
          - 4.2.1 &nbsp; RIP: chapter_route/rip.md
          - 4.2.2 &nbsp; OSPF: chapter_route/ospf.md
  - 第 5 章 &nbsp; 端口隔离 & 端口安全:
      - chapter_cyber_security/index.md
      - 5.1 &nbsp; 端口隔离: chapter_cyber_security/port_isolation.md
      - 5.2 &nbsp; 端口安全: chapter_cyber_security/port_security.md
  # - 第 6 章 &nbsp; ACL:
  #     - chapter_acl/index.md
  #     - 6.1 &nbsp; 基本ACL: chapter_acl/basic.md
  #     - 6.2 &nbsp; 高级ACL: chapter_acl/adv.md
  # - 第 7 章 &nbsp; NAT:
  #     - chapter_nat/index.md
  #     - 6.1 &nbsp; 静态NAT: chapter_nat/static.md
  #     - 6.2 &nbsp; 动态NAT & PAT: chapter_nat/dynamic&pat.md
